services:
  db:
    image: postgres:15
    container_name: grand_sampan_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: grand_sampan
    ports:
      - "5433:5432"
    volumes:
      - grand_sampan_db_data:/var/lib/postgresql/data

volumes:
  grand_sampan_db_data:
