'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { formatMoney } from '@/lib/format';
import MoneyDisplay from '@/components/ui/MoneyDisplay';
import StatCard from '@/components/ui/StatCard';
import Badge from '@/components/ui/Badge';
import Button from '@/components/Button';

type SuiteTier = 'Standard' | 'Delux' | 'Premium';

const SUITE_DEFAULTS: Record<SuiteTier, { price: number; adr: number; size: number }> = {
  Standard: { price: 1500000, adr: 8500, size: 250 },
  Delux: { price: 2200000, adr: 12000, size: 320 },
  Premium: { price: 3200000, adr: 17500, size: 450 }
};

export default function ReturnsIncomePage() {
  const [tier, setTier] = useState<SuiteTier>('Delux');
  const [personalStayDays, setPersonalStayDays] = useState(5); // days per month
  const [occupancyPct, setOccupancyPct] = useState(70); // %
  const [customAdr, setCustomAdr] = useState<number>(12000);
  const [investmentAmount, setInvestmentAmount] = useState<number>(2200000);

  // Update defaults when tier changes
  function onTierSelect(selected: SuiteTier) {
    setTier(selected);
    setCustomAdr(SUITE_DEFAULTS[selected].adr);
    setInvestmentAmount(SUITE_DEFAULTS[selected].price);
  }

  const calculation = useMemo(() => {
    const daysInYear = 365;
    const personalDaysPerYear = personalStayDays * 12;
    const availableRentalDays = Math.max(0, daysInYear - personalDaysPerYear);
    const occupiedRentalDays = availableRentalDays * (occupancyPct / 100);

    // Total gross room revenue generated by this share
    const grossAnnualRevenue = occupiedRentalDays * customAdr;

    // Operator split: 60% to investor, 40% to operations, maintenance & management
    const investorAnnualShare = grossAnnualRevenue * 0.6;
    const monthlyDividend = investorAnnualShare / 12;

    // Annual Net Yield on Investment
    const netYieldPct = investmentAmount > 0 ? (investorAnnualShare / investmentAmount) * 100 : 0;

    // 5-Year Cumulative Projection with 5% annual ADR appreciation
    let cumulative5Yr = 0;
    let currentAdr = customAdr;
    for (let yr = 1; yr <= 5; yr++) {
      const yrGross = occupiedRentalDays * currentAdr;
      cumulative5Yr += yrGross * 0.6;
      currentAdr *= 1.05;
    }

    // Est. Payback Horizon
    const paybackYears = investorAnnualShare > 0 ? (investmentAmount / investorAnnualShare).toFixed(1) : '—';

    return {
      availableRentalDays,
      occupiedRentalDays: Math.round(occupiedRentalDays),
      grossAnnualRevenue,
      investorAnnualShare,
      monthlyDividend,
      netYieldPct: netYieldPct.toFixed(2),
      cumulative5Yr,
      paybackYears
    };
  }, [personalStayDays, occupancyPct, customAdr, investmentAmount]);

  return (
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 md:py-14">
      {/* Header */}
      <div className="max-w-3xl">
        <Badge variant="gold" size="sm" dot>Financial Forecasting &amp; Yield Engine</Badge>
        <h1 className="font-display mt-3 text-3xl font-bold text-ocean sm:text-4xl md:text-5xl">
          Transparent Returns &amp; ROI Simulator
        </h1>
        <p className="mt-3 text-sm text-ocean/80 sm:text-base leading-relaxed">
          Grand Sampan operates on a transparent <strong>60/40 revenue share model</strong>. Explore projected monthly dividends, personal stay trade-offs, and multi-year cashflow distributions based on audited Cox&apos;s Bazar hospitality occupancy data.
        </p>
      </div>

      {/* Tier Selector */}
      <div className="mt-8 flex flex-wrap items-center gap-3 border-b border-ocean/10 pb-5">
        <span className="text-xs font-bold uppercase tracking-wider text-ocean/60">Select Suite Tier:</span>
        {(['Standard', 'Delux', 'Premium'] as SuiteTier[]).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => onTierSelect(t)}
            className={`rounded-full px-5 py-2 text-xs font-bold transition-all ${
              tier === t
                ? 'bg-ocean text-gold shadow-md ring-2 ring-gold/40'
                : 'border border-ocean/15 bg-white text-ocean/70 hover:border-ocean/30 hover:text-ocean'
            }`}
          >
            {t} Suite ({SUITE_DEFAULTS[t].size} sq ft)
          </button>
        ))}
      </div>

      <div className="mt-8 grid gap-8 lg:grid-cols-12">
        {/* Left Column: Interactive Sliders & Controls */}
        <div className="space-y-6 lg:col-span-6">
          {/* Slider 1: Investment Value */}
          <div className="rounded-xl border border-ocean/10 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold uppercase tracking-wider text-ocean/70">
                Share Investment Price
              </label>
              <span className="font-display text-lg font-bold text-ocean">
                {formatMoney(investmentAmount)}
              </span>
            </div>
            <input
              type="range"
              min={1000000}
              max={5000000}
              step={100000}
              value={investmentAmount}
              onChange={(e) => setInvestmentAmount(Number(e.target.value))}
              className="mt-3 h-2 w-full cursor-pointer accent-gold"
            />
            <div className="mt-1 flex justify-between text-[11px] text-ocean/50">
              <span>৳10,00,000</span>
              <span>৳30,00,000</span>
              <span>৳50,00,000</span>
            </div>
          </div>

          {/* Slider 2: Occupancy Rate */}
          <div className="rounded-xl border border-ocean/10 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-xs font-bold uppercase tracking-wider text-ocean/70">
                  Annual Average Occupancy
                </label>
                <p className="text-[11px] text-ocean/55">Inani Beach avg: 65% - 78%</p>
              </div>
              <span className="font-display text-xl font-bold text-ocean">{occupancyPct}%</span>
            </div>
            <input
              type="range"
              min={40}
              max={95}
              step={5}
              value={occupancyPct}
              onChange={(e) => setOccupancyPct(Number(e.target.value))}
              className="mt-3 h-2 w-full cursor-pointer accent-gold"
            />
            <div className="mt-2 flex gap-2">
              {[
                { label: 'Conservative (55%)', val: 55 },
                { label: 'Expected (70%)', val: 70 },
                { label: 'Peak (85%)', val: 85 }
              ].map((sc) => (
                <button
                  key={sc.label}
                  type="button"
                  onClick={() => setOccupancyPct(sc.val)}
                  className={`rounded-md px-2.5 py-1 text-[11px] font-semibold transition ${
                    occupancyPct === sc.val
                      ? 'bg-ocean text-white'
                      : 'bg-pearl text-ocean/70 hover:bg-ocean/10'
                  }`}
                >
                  {sc.label}
                </button>
              ))}
            </div>
          </div>

          {/* Slider 3: Personal Usage Days */}
          <div className="rounded-xl border border-ocean/10 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-xs font-bold uppercase tracking-wider text-ocean/70">
                  Personal Vacation Stay (Days/Month)
                </label>
                <p className="text-[11px] text-ocean/55">
                  {personalStayDays * 12} days free stay / year for you &amp; family
                </p>
              </div>
              <span className="font-display text-xl font-bold text-ocean">
                {personalStayDays} <span className="text-xs font-normal">days/mo</span>
              </span>
            </div>
            <input
              type="range"
              min={0}
              max={15}
              step={1}
              value={personalStayDays}
              onChange={(e) => setPersonalStayDays(Number(e.target.value))}
              className="mt-3 h-2 w-full cursor-pointer accent-gold"
            />
            <div className="mt-1 flex justify-between text-[11px] text-ocean/50">
              <span>0 days (Max Cash Yield)</span>
              <span>5 days (Standard)</span>
              <span>15 days (High Lifestyle)</span>
            </div>
          </div>

          {/* Slider 4: Average Daily Rate (ADR) */}
          <div className="rounded-xl border border-ocean/10 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold uppercase tracking-wider text-ocean/70">
                Average Daily Rental Rate (ADR)
              </label>
              <span className="font-display text-lg font-bold text-ocean">
                {formatMoney(customAdr)} / night
              </span>
            </div>
            <input
              type="range"
              min={5000}
              max={30000}
              step={500}
              value={customAdr}
              onChange={(e) => setCustomAdr(Number(e.target.value))}
              className="mt-3 h-2 w-full cursor-pointer accent-gold"
            />
          </div>
        </div>

        {/* Right Column: Visual Breakdown & Dividend Cards */}
        <div className="space-y-6 lg:col-span-6">
          {/* Main Dividend Result Card */}
          <div className="relative overflow-hidden rounded-2xl border border-gold/40 bg-gradient-to-br from-ocean via-[#0b2d47] to-ocean-dark p-6 text-white shadow-xl">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-gold">
                Investor Dividend Projection
              </span>
              <Badge variant="gold" size="sm">60% Net Share</Badge>
            </div>

            <div className="mt-4 grid grid-cols-2 gap-4 border-b border-white/10 pb-5">
              <div>
                <p className="text-xs text-white/60">Estimated Monthly Dividend</p>
                <div className="mt-1 font-display text-2xl font-bold text-white sm:text-3xl">
                  {formatMoney(calculation.monthlyDividend)}
                </div>
              </div>
              <div>
                <p className="text-xs text-white/60">Annual Net Yield (ROI)</p>
                <div className="mt-1 font-display text-2xl font-bold text-emerald-400 sm:text-3xl">
                  {calculation.netYieldPct}%
                </div>
              </div>
            </div>

            <div className="mt-4 grid grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-white/60 block">Annual Net Payout</span>
                <span className="font-bold text-white text-base sm:text-lg">
                  {formatMoney(calculation.investorAnnualShare)}
                </span>
              </div>
              <div>
                <span className="text-white/60 block">Est. Payback Horizon</span>
                <span className="font-bold text-gold text-base sm:text-lg">
                  {calculation.paybackYears} Years
                </span>
              </div>
            </div>

            {/* 5-Year Milestone Highlight */}
            <div className="mt-5 rounded-xl border border-white/15 bg-white/10 p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-xs font-semibold text-gold">5-Year Cumulative Cash Return</p>
                  <p className="text-[11px] text-white/70">With 5% compound room rate appreciation</p>
                </div>
                <div className="font-display text-lg font-bold text-white">
                  {formatMoney(calculation.cumulative5Yr)}
                </div>
              </div>
            </div>
          </div>

          {/* Revenue Distribution Diagram */}
          <div className="rounded-xl border border-ocean/10 bg-white p-5 shadow-sm">
            <h3 className="font-display text-lg font-bold text-ocean">Annual Revenue Distribution Model</h3>
            
            <div className="mt-4 space-y-3">
              <div>
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-ocean">Investor Payout (60%)</span>
                  <span className="text-ocean font-bold">{formatMoney(calculation.investorAnnualShare)}</span>
                </div>
                <div className="mt-1 h-3 w-full overflow-hidden rounded-full bg-pearl">
                  <div className="h-full bg-ocean rounded-full" style={{ width: '60%' }} />
                </div>
              </div>

              <div>
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-ocean/70">Hotel Operations, Staff &amp; Marketing (25%)</span>
                  <span className="text-ocean/70">{formatMoney(calculation.grossAnnualRevenue * 0.25)}</span>
                </div>
                <div className="mt-1 h-2.5 w-full overflow-hidden rounded-full bg-pearl">
                  <div className="h-full bg-gold rounded-full" style={{ width: '25%' }} />
                </div>
              </div>

              <div>
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-ocean/70">Maintenance &amp; FF&amp;E Reserve Fund (15%)</span>
                  <span className="text-ocean/70">{formatMoney(calculation.grossAnnualRevenue * 0.15)}</span>
                </div>
                <div className="mt-1 h-2.5 w-full overflow-hidden rounded-full bg-pearl">
                  <div className="h-full bg-stone-400 rounded-full" style={{ width: '15%' }} />
                </div>
              </div>
            </div>

            <div className="mt-6 flex flex-col gap-3 sm:flex-row">
              <Link href="/invest" className="flex-1">
                <Button className="w-full">Explore Available Share Plans</Button>
              </Link>
              <Link href="/invest/advisor" className="flex-1">
                <Button variant="outline" className="w-full">Ask AI Advisor</Button>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
